### ISSUE TITLE
when a medic starts a revive the the coundown will continue resenting and will not stop at 0

### ISSUE THREAD

**Issue by KrisMultiDev** [CultureConnectionLnu/hunger-games#27]
How to repeat:
Select dead player
Press Start revive
Close that player's revive screen.
(keeping the player's revive options screen open when the countdown hits 0 will stop this from happening but if missed the countdown will repeat itself constantly)
This can also be fixed by resetting the page

**Comment by NicoVogel** [comment]
Fixed by #31 31
